services:
  backend:
    build: . 
    ports:
      - "3000:3000"
    environment:
      FRONTEND_DEV_SEVER: "http://localhost:5173"
      MONGO_DB_STRING : "mongodb://mongodb:27017/bonsai-dev-database"
      PORT : "3000"
      NODE_ENV: "dev"
      REFRESH_TOKEN_SECRET: "UYzCnj0exk8K3WIku4xrNbdFdiR0piRYSMMK1PI7ndSQ3DgIGgPjQcvI/KROFbB1CZD8V+5myqjYMXaGpHPlLg=="
      ACCESS_TOKEN_SECRET: "+gseK9cQ1TDN53RXNfKZrsTOyJoGcD9qK3Mx0VSdoc2jNygFPVHwuSrwWmns7IPiPT+1gwaV/FZ3O/GpevfwWg=="
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - mongodb
    command: npm run dev
    
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"